name: Build LGPL mpv

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git meson ninja-build devscripts \
              libavcodec-dev libavfilter-dev libavformat-dev libswscale-dev libswresample-dev \
              libjpeg-dev libx11-dev libxext-dev libxinerama-dev libfreetype6-dev libfontconfig-dev \
              libfribidi-dev libharfbuzz-dev libass-dev

      - name: Build and install libplacebo
        run: |
          git clone --depth=1 --recursive https://github.com/haasn/libplacebo.git
          cd libplacebo
          meson setup build
          sudo ninja -C build install

      - name: Get mpv source
        run: git clone --depth=1 https://github.com/mpv-player/mpv.git

      - name: Configure and build mpv with LGPL option
        run: |
          cd mpv
          meson setup build -Dgpl=false
          ninja -C build

      - name: Create deb package with dpkg-deb
        id: create-package
        run: |
          MPV_VERSION="0.40.0"
          DEB_PACKAGE_NAME="mpv-lgpl_${MPV_VERSION}-1_amd64.deb"
          DEB_DIR="debian_pkg"
          MPV_BUILD_DIR="mpv/build"

          mkdir -p "$DEB_DIR/usr/local/bin"
          mkdir -p "$DEB_DIR/usr/local/lib/x86_64-linux-gnu"
          mkdir -p "$DEB_DIR/DEBIAN"

          # ファイルをコピー
          cp "$MPV_BUILD_DIR/mpv" "$DEB_DIR/usr/local/bin/"
          cp "$MPV_BUILD_DIR/libmpv.so.2.5.0" "$DEB_DIR/usr/local/lib/x86_64-linux-gnu/"

          # libmpv.soのシンボリックリンクを作成
          (cd "$DEB_DIR/usr/local/lib/x86_64-linux-gnu/" && ln -s libmpv.so.2.5.0 libmpv.so.2)
          (cd "$DEB_DIR/usr/local/lib/x86_64-linux-gnu/" && ln -s libmpv.so.2 libmpv.so)

          # controlファイルを作成
          cat > "$DEB_DIR/DEBIAN/control" <<EOF
          Package: mpv-lgpl
          Version: ${MPV_VERSION}
          Section: video
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: A media player LGPLv2.1 or later.
           mpv is a free and open-source command-line media player.
           This package is built with LGPLv2.1+ only files.
          Depends: libavcodec-dev, libavfilter-dev, libavformat-dev, libswresample-dev, libswscale-dev, libjpeg-dev, libx11-dev, libxext-dev, libxinerama-dev, libfreetype6-dev, libfontconfig-dev, libfribidi-dev, libharfbuzz-dev, libass-dev
          EOF

          # debパッケージをビルド
          dpkg-deb --build "$DEB_DIR" "$DEB_PACKAGE_NAME"
          echo "DEB_PATH=$DEB_PACKAGE_NAME" >> "$GITHUB_OUTPUT"
      
      - name: Upload deb package to a temporary artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpv-lgpl-deb-package
          path: ${{ steps.create-package.outputs.DEB_PATH }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.create-package.outputs.DEB_PATH }}
          asset_name: ${{ steps.create-package.outputs.DEB_PATH }}
          asset_content_type: application/vnd.debian.binary-package
