name: Build LGPL mpv

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git libjpeg-dev libx11-dev libxext-dev libxinerama-dev libfreetype6-dev libfontconfig-dev checkinstall meson ninja-build libavcodec-dev libavformat-dev libswscale-dev libavfilter-dev

      - name: Get mpv and libplacebo sources
        run: |
          git clone --depth=1 https://github.com/mpv-player/mpv.git
          git clone --depth=1 https://github.com/haasn/libplacebo.git
          mv libplacebo mpv/subprojects/

      - name: Configure and Build mpv with LGPL option
        run: |
          cd mpv
          meson setup build -Dgpl=false
          ninja -C build

      - name: Create deb package
        run: |
          cd mpv
          sudo ninja -C build install
          sudo checkinstall -y --pkgname=mpv-lgpl --pkgversion=1:0.40.0 --maintainer="Your Name <your.email@example.com>" --pakdir=/tmp/
          
      - name: Upload deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpv-lgpl-deb-package
          path: /tmp/*.deb
